config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "index", to: "tasks#index"
  get "tasks/new", to: "tasks#new", as: "new_task"
  post "tasks", to: "tasks#create"
  get "tasks/:id", to: "tasks#show", as: "task"
  get "tasks/:id/edit", to: "tasks#edit", as: "edit_task"
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      redirect_to tasks_path
    else
      redirect_to tasks_path, status: :see_other
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>

<%= form_with model: @task do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :details, 'Description' %>
    <%= f.text_area :details %>
  </div>
  <div>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>
  <div>
    <%= f.submit 'Edit Task' %>
  </div>
<% end %>

<%= link_to 'Back to list', index_path %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
    <%= link_to task.title, task_path(task) %>
    <%= check_box_tag 'task_ids[]', task.id, task.completed, class: 'form-check-input' %>
    <%= link_to "Edit", edit_task_path(task), class: 'btn btn-primary btn-sm' %>
    </li>
  <% end %>
</ul>

<%= link_to "Add a new task", new_task_path(new_task_url) %>

app/views/tasks/new.html.erb
<h2>New Task</h2>

<%= form_with model: @task do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :details, 'Description' %>
    <%= f.text_area :details %>
  </div>
  <div>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  </div>
  <div>
    <%= f.submit 'Create Task' %>
  </div>
<% end %>

<%= link_to 'Back to list', index_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>

<p><%= @task.details %></p>

<div>
Completed:
<%= check_box_tag 'task[completed]', @task.completed, @task.completed, class: 'form-check-input' %>
</div>
<%= link_to "Delete", task_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

<%= link_to 'Back to', index_path %>